[package]
name = "oden"
version = "0.1.0"
edition = "2024"

[dependencies]
anvil = { git = "https://github.com/paramatrix-dev/anvil.git", branch = "main" }
clap = { version = "4.5.32", features = ["derive"] }
dyn-clone = "1.0.19"
regex = "1.11.1"
